/** Category of alert generated by the alert engine. */
export type AlertCategory =
  | 'Fund Performance'
  | 'Fund Manager Change'
  | 'House View Review'
  | 'Portfolio Drift'
  | 'Governance Review'
  | 'Research Review'
  | 'Compliance Review';

/** Severity level for alert triage. */
export type AlertSeverity = 'Low' | 'Medium' | 'High' | 'Critical';

/** Lifecycle status of an alert before inbox conversion. */
export type AlertStatus = 'Open' | 'Acknowledged' | 'Resolved' | 'Dismissed';

/** How the alert was produced by the alert engine. */
export type AlertOrigin = 'static_mock' | 'rule_generated';

/** A platform alert that may feed the research inbox workflow. */
export type Alert = {
  id: string;
  title: string;
  summary: string;
  category: AlertCategory;
  severity: AlertSeverity;
  status: AlertStatus;
  /** Static mock data or output from alert rule evaluation. */
  origin: AlertOrigin;
  /** ISO timestamp when the alert was created. */
  createdAt: string;
  relatedEntityId?: string | null;
  /** When origin is rule_generated, the source alert rule id. */
  sourceRuleId?: string | null;
};

export type AlertInput = {
  alerts: Alert[];
};

export type AlertSummary = {
  totalAlerts: number;
  criticalAlerts: number;
  highAlerts: number;
  openAlerts: number;
  acknowledgedAlerts: number;
  resolvedAlerts: number;
  dismissedAlerts: number;
  staticMockAlerts: number;
  ruleGeneratedAlerts: number;
};

export type AlertEngineResult = {
  sortedAlerts: Alert[];
  summary: AlertSummary;
};
