import type { WeeklyBrief } from '../../domain/types/weekly-brief';
import { formatIsoTimestampDisplay } from '../../lib/format-timestamp';
import StatusBox from './StatusBox';

export default function MacroWatchPanel({ brief }: { brief: WeeklyBrief | null }) {
  return (
    <section style={card}>
      <h3 style={title}>Macro & market watch</h3>
      <StatusBox variant="neutral" display="inline">
        Live — generated by the weekly research brief engine.
      </StatusBox>

      {!brief && (
        <p style={emptyText}>
          No weekly brief has been generated yet. Run it from the Research page
          to populate this section.
        </p>
      )}

      {brief && (
        <>
          <p style={weekOf}>Week of {formatIsoTimestampDisplay(`${brief.weekOf}T00:00:00.000Z`)}</p>
          <p style={macroText}>{brief.macroSummary}</p>

          {brief.securityAlerts.length > 0 && (
            <div style={group}>
              <h4 style={groupTitle}>Security alerts</h4>
              <ul style={list}>
                {brief.securityAlerts.map((alert, i) => (
                  <li key={`${alert.ticker}-${i}`} style={row}>
                    <span style={rowTitle}>{alert.ticker} — {alert.headline}</span>
                    <span style={rowMeta}>{alert.detail}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {brief.alternativeFlags.length > 0 && (
            <div style={group}>
              <h4 style={groupTitle}>Best-in-class alternative flags</h4>
              <ul style={list}>
                {brief.alternativeFlags.map((flag, i) => (
                  <li key={`${flag.ticker}-${i}`} style={row}>
                    <span style={rowTitle}>{flag.name} ({flag.ticker}) → {flag.alternative}</span>
                    <span style={rowMeta}>{flag.rationale}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {brief.securityAlerts.length === 0 && brief.alternativeFlags.length === 0 && (
            <p style={emptyText}>Nothing flagged this week beyond the macro summary above.</p>
          )}
        </>
      )}
    </section>
  );
}

const card = {
  padding: '20px',
  background: '#0d2a4d',
  borderRadius: '14px',
  border: '1px solid #2d4a6b',
};

const title = {
  margin: '0 0 10px 0',
  fontSize: '17px',
  fontWeight: 600,
};

const weekOf = {
  margin: '14px 0 6px 0',
  fontSize: '12px',
  color: '#94a3b8',
};

const macroText = {
  margin: 0,
  fontSize: '14px',
  lineHeight: 1.5,
  color: '#e2e8f0',
};

const group = {
  marginTop: '16px',
};

const groupTitle = {
  margin: '0 0 8px 0',
  fontSize: '13px',
  fontWeight: 600,
  color: '#94a3b8',
  textTransform: 'uppercase' as const,
  letterSpacing: '0.04em',
};

const list = {
  margin: 0,
  padding: 0,
  listStyle: 'none',
  display: 'flex',
  flexDirection: 'column' as const,
  gap: '8px',
};

const row = {
  display: 'flex',
  flexDirection: 'column' as const,
  gap: '2px',
  padding: '10px 12px',
  background: '#12345b',
  borderRadius: '8px',
  border: '1px solid #2d4a6b',
};

const rowTitle = {
  fontSize: '14px',
  fontWeight: 600,
};

const rowMeta = {
  fontSize: '12px',
  color: '#94a3b8',
};

const emptyText = {
  margin: '12px 0 0 0',
  fontSize: '13px',
  color: '#94a3b8',
  fontStyle: 'italic' as const,
};
